export BOHRIUM_BOHRIUM_URL="https://bohrium.test.dp.tech"
export BOHRIUM_TIEFBLUE_URL="https://tiefblue.test.dp.tech"
export BOHRIUM_OPENAPI_URL="https://openapi.test.dp.tech"
export BOHRIUM_BASE_URL="https://openapi.test.dp.tech"
export TIEFBLUE_BASE_URL="https://tiefblue-zjk-test.test.dp.tech"